[package]
name = "metewand-protocol"
description = "Versioned worker protocol types for Metewand"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true
