#!/usr/bin/env python3

import sys

sys.dont_write_bytecode = True

from fixture_worker import die, run_protocol_failure


if len(sys.argv) != 2:
    die("usage: protocol-failure MODE")
raise SystemExit(run_protocol_failure(sys.argv[1]))
